### ISSUE TITLE
errors running demo

### ISSUE THREAD

**Issue by travischoma** [acdlite/flummox-isomorphic-demo#1]
I had do to npm install -g nodemon to get 'make watch' to work.

Once I did that the demo app crashed because of a missing module: Error: Cannot find module 'source-map-support'

Once I installed source-map-support with npm that was solved butI got the following error

.../flummox-isomorphic-demo/node_modules/koa/lib/application.js:174
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)

**Comment by acdlite** [comment]
Ah, I assume you're not running iojs?

**Comment by acdlite** [comment]
Added source-map-support as a devDependency 7da74ac3bda243ce55017ca3d90054b8586e0bfa

**Comment by travischoma** [comment]
thanks, yes now running with iojs :-)

**Comment by acdlite** [comment]
Sweet, sorry for the hiccups :) I whipped this together pretty quickly so it still needs a lot of work

**Comment by travischoma** [comment]
FYI i only see the following message on the page port 3000, should there be something else, don't see the github stargazers afaik?:
"Isomorphic Flummox App

This is an simple app demonstrating how to use Flummox and react-router to create isomorphic React applications.

It's a work in progress. Right now, it shows the first 50 stargazers for a given GitHub repo. Pretty bare-bones, as you can see, but it gets the basic idea across.

Check out the page source to see that HTML is being rendered on the server."

**Comment by acdlite** [comment]
Go to localhost:3000/stargazers/acdlite/flummox (or any other repo)

**Comment by travischoma** [comment]
got it, thx!
